# Étape 1 : Image de base avec Node.js
FROM node:18-slim

# Étape 2 : Créer un répertoire de travail
WORKDIR /app

# Étape 3 : Copier les fichiers JS
COPY / ./

# Étape 4 : Définir le point d’entrée
ENTRYPOINT ["node", "SSP.js"]
