FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY SSPApp/ ./SSPApp/
WORKDIR /src/SSPApp

RUN dotnet restore
RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

COPY --from=build /app .
ENTRYPOINT ["dotnet", "SSPApp.dll"]
