# Use an official Scala runtime as a parent image
FROM openjdk:8-jre-slim
# Set the working directory to /app
WORKDIR /app
# Copy the current directory contents into the container at /app
COPY . /app
# Install Scala
RUN apt-get update && \
    apt-get install -y scala
# Compile the Scala code
CMD ["scala", "SSP"]